version: "3.1"
services:
  web:
    environment:
      RACK_ENV: none
      APP_ENV: production
      REDIS_HOST: redis
      SECRET: /run/secrets/secret
    secrets:
      - secret
    image: kostyadubinin/cards
    ports:
      - "80:9292"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet:
secrets:
   secret:
     external: true
