version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    secrets:
      - site.key
      - site.crt
    volumes:
      - /mnt/volume_ams3_01/nginx.conf:/etc/nginx/nginx.conf
  web:
    secrets:
      - password
    environment:
      PASSWORD_PATH: "/run/secrets/password"
      RACK_ENV: none
      APP_ENV: production
      REDIS_HOST: redis
    image: kostyadubinin/cards
    ports:
      - "9292:9292"
    networks:
      - webnet
  redis:
    image: redis
    volumes:
        - /mnt/volume_ams3_01:/data
    networks:
      - webnet
networks:
  webnet:
secrets:
   password:
     external: true
   site.key:
     external: true
   site.crt:
     external: true
