version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - webnet
    environment:
      SSL_KEY_PATH: /run/secrets/ssl_key_path
      SSL_CERT_PATH: /run/secrets/ssl_cert_path
    secrets:
      - ssl_key_path
      - ssl_cert_path
  web:
    environment:
      RACK_ENV: none
      APP_ENV: production
      REDIS_HOST: redis
      SECRET: /run/secrets/secret
    secrets:
      - secret
    image: kostyadubinin/cards
    ports:
      - "9292:9292"
    networks:
      - webnet
  redis:
    image: redis
    volumes:
        - /mnt/volume_ams3_01:/data
    networks:
      - webnet
networks:
  webnet:
secrets:
   secret:
     external: true
   ssl_key_path:
     external: true
   ssl_cert_path:
     external: true
