---
- hosts: all
  remote_user: root
  tasks:
    - name: copy docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /root/docker-compose.yml
    - name: copy nginx.conf
      copy:
        src: nginx.conf
        dest: /mnt/volume_ams3_01
    - name: deploy
      command: docker stack deploy -c docker-compose.yml --with-registry-auth cards
